import { type MigrationInterface, type QueryRunner } from 'typeorm'

export class SchemaUpdate1754661428551 implements MigrationInterface {
  name = 'SchemaUpdate1754661428551'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE TABLE `auths` (`uuid` varchar(36) NOT NULL, `refreshToken` text NOT NULL, `accessToken` text NOT NULL, `valid` tinyint NOT NULL DEFAULT 1, `expireAt` date NOT NULL, `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `mpath` varchar(255) NULL DEFAULT \'\', `parentUuid` varchar(36) NULL, `userId` int NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB')
    await queryRunner.query('CREATE TABLE `item_category` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, UNIQUE INDEX `IDX_3776df63b26aee9f2089a70403` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB')
    await queryRunner.query('CREATE TABLE `item_tags` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `notes` `notes` text NULL')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `itemId` `itemId` int NULL')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `projectId` `projectId` int NULL')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `userId` `userId` int NULL')
    await queryRunner.query('ALTER TABLE `project_memberships` CHANGE `userId` `userId` int NULL')
    await queryRunner.query('ALTER TABLE `project_memberships` CHANGE `projectId` `projectId` int NULL')
    await queryRunner.query('ALTER TABLE `projects` CHANGE `ownerId` `ownerId` int NULL')
    await queryRunner.query('ALTER TABLE `items` CHANGE `description` `description` varchar(255) NULL')
    await queryRunner.query('ALTER TABLE `items` CHANGE `location` `location` varchar(255) NULL')
    await queryRunner.query('ALTER TABLE `items` CHANGE `price` `price` decimal(10,2) NULL')
    await queryRunner.query('ALTER TABLE `items` CHANGE `acquisitionAt` `acquisitionAt` datetime NULL')
    await queryRunner.query('ALTER TABLE `items` CHANGE `projectId` `projectId` int NULL')
    await queryRunner.query('ALTER TABLE `groups` CHANGE `description` `description` varchar(2048) NULL')
    await queryRunner.query('ALTER TABLE `groups` CHANGE `categoryId` `categoryId` int NULL')
    await queryRunner.query('ALTER TABLE `auths` ADD CONSTRAINT `FK_0f848d4b3817a1a64bda88ba179` FOREIGN KEY (`parentUuid`) REFERENCES `auths`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `auths` ADD CONSTRAINT `FK_3e65bf4e56bde80b7b5e5b9e133` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `item_movements` ADD CONSTRAINT `FK_7c9e6b3ee93fa4efcf3c0348b85` FOREIGN KEY (`itemId`) REFERENCES `items`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `item_movements` ADD CONSTRAINT `FK_a7ea2d4caeddd4f48eb191ef7f1` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `item_movements` ADD CONSTRAINT `FK_658451fa4e409c218b34df4b7f9` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `project_memberships` ADD CONSTRAINT `FK_bd67b3007ede89cb06a0c8a5abd` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `project_memberships` ADD CONSTRAINT `FK_5f19347882ccafc35f4c7293abd` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `projects` ADD CONSTRAINT `FK_a8e7e6c3f9d9528ed35fe5bae33` FOREIGN KEY (`ownerId`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `items` ADD CONSTRAINT `FK_74ea578106741b6b05076cfbf1c` FOREIGN KEY (`groupId`) REFERENCES `groups`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `items` ADD CONSTRAINT `FK_2e6abb90fe7574a3734c2b7e293` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `files` ADD CONSTRAINT `FK_dbd64f45bf3535f311a03207d39` FOREIGN KEY (`groupId`) REFERENCES `groups`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `groups` ADD CONSTRAINT `FK_9d7cca97a960def5de2629571bb` FOREIGN KEY (`categoryId`) REFERENCES `item_category`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE `groups_tags_item_tags` ADD CONSTRAINT `FK_17adbcebc986f3ef98931a53a33` FOREIGN KEY (`groupsId`) REFERENCES `groups`(`id`) ON DELETE CASCADE ON UPDATE CASCADE')
    await queryRunner.query('ALTER TABLE `groups_tags_item_tags` ADD CONSTRAINT `FK_20ab5a72456d84cdc3c2409d9b8` FOREIGN KEY (`itemTagsId`) REFERENCES `item_tags`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION')
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE `groups_tags_item_tags` DROP FOREIGN KEY `FK_20ab5a72456d84cdc3c2409d9b8`')
    await queryRunner.query('ALTER TABLE `groups_tags_item_tags` DROP FOREIGN KEY `FK_17adbcebc986f3ef98931a53a33`')
    await queryRunner.query('ALTER TABLE `groups` DROP FOREIGN KEY `FK_9d7cca97a960def5de2629571bb`')
    await queryRunner.query('ALTER TABLE `files` DROP FOREIGN KEY `FK_dbd64f45bf3535f311a03207d39`')
    await queryRunner.query('ALTER TABLE `items` DROP FOREIGN KEY `FK_2e6abb90fe7574a3734c2b7e293`')
    await queryRunner.query('ALTER TABLE `items` DROP FOREIGN KEY `FK_74ea578106741b6b05076cfbf1c`')
    await queryRunner.query('ALTER TABLE `projects` DROP FOREIGN KEY `FK_a8e7e6c3f9d9528ed35fe5bae33`')
    await queryRunner.query('ALTER TABLE `project_memberships` DROP FOREIGN KEY `FK_5f19347882ccafc35f4c7293abd`')
    await queryRunner.query('ALTER TABLE `project_memberships` DROP FOREIGN KEY `FK_bd67b3007ede89cb06a0c8a5abd`')
    await queryRunner.query('ALTER TABLE `item_movements` DROP FOREIGN KEY `FK_658451fa4e409c218b34df4b7f9`')
    await queryRunner.query('ALTER TABLE `item_movements` DROP FOREIGN KEY `FK_a7ea2d4caeddd4f48eb191ef7f1`')
    await queryRunner.query('ALTER TABLE `item_movements` DROP FOREIGN KEY `FK_7c9e6b3ee93fa4efcf3c0348b85`')
    await queryRunner.query('ALTER TABLE `auths` DROP FOREIGN KEY `FK_3e65bf4e56bde80b7b5e5b9e133`')
    await queryRunner.query('ALTER TABLE `auths` DROP FOREIGN KEY `FK_0f848d4b3817a1a64bda88ba179`')
    await queryRunner.query('ALTER TABLE `groups` CHANGE `categoryId` `categoryId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `groups` CHANGE `description` `description` varchar(2048) NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `items` CHANGE `projectId` `projectId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `items` CHANGE `acquisitionAt` `acquisitionAt` datetime NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `items` CHANGE `price` `price` decimal(10,2) NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `items` CHANGE `location` `location` varchar(255) NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `items` CHANGE `description` `description` varchar(255) NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `projects` CHANGE `ownerId` `ownerId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `project_memberships` CHANGE `projectId` `projectId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `project_memberships` CHANGE `userId` `userId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `userId` `userId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `projectId` `projectId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `itemId` `itemId` int NULL DEFAULT \'NULL\'')
    await queryRunner.query('ALTER TABLE `item_movements` CHANGE `notes` `notes` text NULL DEFAULT \'NULL\'')
    await queryRunner.query('DROP TABLE `item_tags`')
    await queryRunner.query('DROP INDEX `IDX_3776df63b26aee9f2089a70403` ON `item_category`')
    await queryRunner.query('DROP TABLE `item_category`')
    await queryRunner.query('DROP TABLE `auths`')
  }

}
